"""Aggregate the experiment runs into the paper's canonical row set, tables, and macros.

Reads every outputs/runs/*/results.csv (schemas differ across runs), normalizes legacy
column names, keeps successfully scored rows, dedupes by output stem (latest run wins),
and emits:
  data/canonical_rows.csv   traceable row set (+run_id)
  tables/main_results.tex   Table 1 body
  tables/setup_models.tex   model/endpoint/cost table body
  tables/numbers.tex        \\newcommand macros for every number quoted in prose
"""

import random
import sys

import pandas as pd
import yaml
from config import (
    CANONICAL_RUN_PREFIXES,
    CONTROL_NAMES,
    DATA_DIR,
    METRIC_COLS,
    MODEL_CONFIGS_DIR,
    MODEL_NAMES,
    PROCEDURE_NAMES,
    RUNS_DIR,
    TABLES_DIR,
    read_text,
    tex_escape,
    write_text,
)

GENERATED_BY = "% Generated by scripts/aggregate.py - do not edit by hand.\n"


def load_runs() -> pd.DataFrame:
    frames = []
    for csv in sorted(RUNS_DIR.glob("*/results.csv")):
        if not csv.parent.name.startswith(CANONICAL_RUN_PREFIXES):
            continue
        frames.append(pd.read_csv(csv).assign(run_id=csv.parent.name))
    if not frames:
        sys.exit(f"No results.csv found under {RUNS_DIR}")
    return pd.concat(frames, ignore_index=True, sort=False)


def normalize(df: pd.DataFrame) -> pd.DataFrame:
    # Early facelift runs predate the target/offtarget naming; for those runs the
    # lower face IS the target region and the upper face the keep zone.
    df["legacy_regions"] = False
    if "change_lower_face" in df.columns:
        legacy = df["change_target"].isna() & df["change_lower_face"].notna()
        df.loc[legacy, "change_target"] = df.loc[legacy, "change_lower_face"]
        df.loc[legacy, "change_offtarget"] = df.loc[legacy, "change_upper_face"]
        df.loc[legacy, "legacy_regions"] = True
    df["procedure"] = df["procedure"].replace({"facelift": "deep_plane_facelift"})
    return df


def dedupe(df: pd.DataFrame) -> pd.DataFrame:
    # Per stem keep the row with the most populated metrics; break ties by latest run
    # (some later runs replayed stems in an environment missing the eval extras, so
    # plain latest-wins would discard scored rows).
    df = df.assign(_n_metrics=df[METRIC_COLS].notna().sum(axis=1))
    df = df.sort_values(["_n_metrics", "run_id"])
    return df.drop_duplicates("stem", keep="last").drop(columns="_n_metrics")


def fmt(x: float, nd: int = 3) -> str:
    return "--" if pd.isna(x) else f"{x:.{nd}f}"


def med(s: pd.Series, nd: int = 3) -> str:
    return fmt(s.median(), nd)


def latex_table(colspec: str, header: str, rows: list[str]) -> str:
    """A booktabs tabular; `header` and each row are `&`-joined cells without the row end."""
    body = "\n".join(f"{cells} \\\\" for cells in rows)
    return (
        f"{GENERATED_BY}"
        f"\\begin{{tabular}}{{{colspec}}}\n"
        f"\\toprule\n"
        f"{header} \\\\\n"
        f"\\midrule\n"
        f"{body}\n"
        f"\\bottomrule\n"
        f"\\end{{tabular}}\n"
    )


def write_main_results(df: pd.DataFrame) -> None:
    rows = [
        " & ".join([
            PROCEDURE_NAMES.get(proc, tex_escape(proc)),
            MODEL_NAMES.get(model, tex_escape(model)),
            CONTROL_NAMES.get(control, tex_escape(control)),
            str(len(g)),
            f"{med(g.identity_cosine)} {{\\scriptsize({fmt(g.identity_cosine.min())}--{fmt(g.identity_cosine.max())})}}",
            med(g.change_localization),
            med(g.change_target, 1),
            med(g.latency_s, 0),
            med(g.cost_estimate_usd, 3),
        ])
        for (proc, model, control), g in df.groupby(["procedure", "model", "control"], sort=True)
    ]
    write_text(
        TABLES_DIR / "main_results.tex",
        latex_table(
            "lllrlllrr",
            r"Procedure & Model & Control & $n$ & Identity$\uparrow$ & Loc.$\uparrow$ "
            r"& $\Delta E_{\mathrm{tgt}}$ & Lat.\,(s) & Cost\,(\$)",
            rows,
        ),
    )


def write_setup_models() -> None:
    rows = []
    for yml in sorted(MODEL_CONFIGS_DIR.glob("*.yaml")):
        cfg = yaml.safe_load(read_text(yml))
        if cfg.get("type") != "fal":
            continue  # local/open-weight configs exist in the repo but weren't benchmarked
        cost = cfg.get("cost_per_image_usd")
        rows.append(" & ".join([
            MODEL_NAMES.get(cfg["name"], tex_escape(cfg["name"])),
            f"{{\\scriptsize\\texttt{{{tex_escape(cfg.get('model', ''))}}}}}",
            f"{cost:.3f}" if isinstance(cost, (int, float)) else "--",
        ]))
    write_text(
        TABLES_DIR / "setup_models.tex",
        latex_table("llr", r"Model & Endpoint & Cost/image (\$)", rows),
    )


def clustered_median_ci(
    df: pd.DataFrame,
    value_col: str,
    cluster_col: str,
    *,
    n_boot: int = 10_000,
    seed: int = 20_260_717,
) -> tuple[float, float]:
    """Patient-clustered percentile interval for a descriptive median.

    Faces, rather than model outputs, are resampled so the interval does not
    treat multiple editors applied to one photograph as independent patients.
    """
    groups = {
        str(key): group[value_col].dropna().tolist()
        for key, group in df.groupby(cluster_col)
    }
    clusters = list(groups)
    rng = random.Random(seed)
    estimates: list[float] = []
    for _ in range(n_boot):
        values: list[float] = []
        for _ in clusters:
            values.extend(groups[rng.choice(clusters)])
        estimates.append(float(pd.Series(values).median()))
    series = pd.Series(estimates)
    return float(series.quantile(0.025)), float(series.quantile(0.975))


def ci_macros(prefix: str, bounds: tuple[float, float], nd: int = 3) -> dict[str, object]:
    low, high = bounds
    return {f"{prefix}Low": fmt(low, nd), f"{prefix}High": fmt(high, nd)}


def gt_delta_table(single: pd.DataFrame, base: pd.DataFrame) -> pd.DataFrame:
    """Each edit's post-op cosine minus its own face's input-to-post-op baseline."""
    d = single[single.gt_identity_cosine.notna()].merge(
        base, on=["procedure", "face_id"], validate="many_to_one"
    )
    d["delta"] = d.gt_identity_cosine - d.gt_baseline_cosine
    d["face_cluster"] = d.procedure + "/" + d.face_id
    return d


def paired_table(prom: pd.DataFrame, comp: pd.DataFrame) -> pd.DataFrame:
    """Prompt-only vs. masked-composite on the same (procedure, face, model) cell."""
    d = prom.merge(
        comp,
        on=["procedure", "face_id", "model"],
        suffixes=("_prompt", "_composite"),
        validate="one_to_one",
    ).dropna(
        subset=[
            "change_localization_prompt",
            "change_localization_composite",
            "change_offtarget_prompt",
            "change_offtarget_composite",
        ]
    )
    d["face_cluster"] = d.procedure + "/" + d.face_id
    d["localization_gain"] = d.change_localization_composite - d.change_localization_prompt
    d["offtarget_reduction"] = d.change_offtarget_prompt - d.change_offtarget_composite
    return d


def write_numbers(
    df: pd.DataFrame,
    n_runs_total: int,
    n_runs_scored: int,
    n_attempted: int,
) -> None:
    chained = df[df.procedure.str.contains("_then_")]
    single = df[~df.procedure.str.contains("_then_")]
    by_control = {
        "PromptOnly": single[single.control == "prompt_only"],
        "Composite": single[single.control == "masked_composite"],
        "Inpaint": single[single.control == "masked_inpaint"],
    }
    prom, comp, inp = by_control.values()
    below = df[df.identity_cosine < 0.6]
    gt = df.gt_identity_cosine.dropna()

    # Input-to-postoperative baseline (scripts/gt_baseline.py; no generated images
    # involved). Deltas compare each edit's postop cosine against its face's baseline.
    baseline_csv = DATA_DIR / "gt_baseline.csv"
    if not baseline_csv.exists():
        sys.exit("data/gt_baseline.csv missing - run `make baseline` first")
    base = pd.read_csv(baseline_csv)
    gt_delta = gt_delta_table(single, base)
    paired = paired_table(prom, comp)

    # face_id is only unique within a procedure (both real datasets number their
    # faces real_NN), so distinct faces are (procedure, face) pairs, with the two
    # chained orders folded into one procedure so their shared face counts once.
    proc_family = df.procedure.where(~df.procedure.str.contains("_then_"), "chained")

    macros: dict[str, object] = {
        "NumScoredEdits": len(df),
        "NumAttemptedEdits": n_attempted,
        "NumExcludedEdits": n_attempted - len(df),
        "NumRunsTotal": n_runs_total,
        "NumRunsScored": n_runs_scored,
        "NumModelsScored": df.model.nunique(),
        "NumFacesScored": (proc_family + "/" + df.face_id).nunique(),
        "NumPrimaryFaces": (single.procedure + "/" + single.face_id).nunique(),
        "NumLocalizationFaces": paired.face_cluster.nunique(),
        "MedPairedLocGain": med(paired.localization_gain),
        **ci_macros("PairedLocGain", clustered_median_ci(paired, "localization_gain", "face_cluster")),
        "MedPairedOffReduction": med(paired.offtarget_reduction, 2),
        **ci_macros("PairedOffReduction", clustered_median_ci(paired, "offtarget_reduction", "face_cluster"), 2),
        "IdentityMinAll": fmt(df.identity_cosine.min()),
        "IdentityMaxAll": fmt(df.identity_cosine.max()),
        "NumBelowFloor": len(below),
        "NumBelowFloorFlux": len(below[below.model == "flux_2_pro"]),
    }

    # Per-control summaries, kept in lockstep so a new metric lands on all three rungs.
    for suffix, g in by_control.items():
        macros |= {
            f"MedLoc{suffix}": med(g.change_localization),
            f"Loc{suffix}Min": fmt(g.change_localization.min()),
            f"Loc{suffix}Max": fmt(g.change_localization.max()),
            f"MedIdentity{suffix}": med(g.identity_cosine),
            f"MedTgt{suffix}": med(g.change_target, 1),
            f"MedOff{suffix}": med(g.change_offtarget, 2),
        }

    # Model families called out by name in the results prose.
    for suffix, g in [
        ("FluxPromptOnly", df[(df.model == "flux_2_pro") & (df.control == "prompt_only")]),
        ("NanoBanana", df[df.model.isin(["nano_banana_pro", "nano_banana_2"])]),
    ]:
        macros |= {
            f"MedIdentity{suffix}": med(g.identity_cosine),
            f"MedTgt{suffix}": med(g.change_target, 1),
        }

    # The inpaint rung split by procedure; only rhinoplasty's off-target is quoted.
    inp_r = inp[inp.procedure == "rhinoplasty"]
    for suffix, g in [("Facelift", inp[inp.procedure == "deep_plane_facelift"]), ("Rhino", inp_r)]:
        macros |= {
            f"Inpaint{suffix}Loc": med(g.change_localization),
            f"Inpaint{suffix}Identity": med(g.identity_cosine),
            f"Inpaint{suffix}Tgt": med(g.change_target, 1),
        }
    macros["InpaintRhinoOff"] = med(inp_r.change_offtarget, 1)

    macros |= {
        "NumChained": len(chained),
        "ChainedIdentityLow": fmt(chained.identity_cosine.min()),
        "ChainedIdentityHigh": fmt(chained.identity_cosine.max()),
        "ChainedLocLow": fmt(chained.change_localization.min()),
        "ChainedLocHigh": fmt(chained.change_localization.max()),
        "MedGtCosine": med(gt),
        "GtCosineMin": fmt(gt.min()),
        "GtCosineMax": fmt(gt.max()),
        "MedGtCosineFacelift": med(df[df.procedure == "deep_plane_facelift"].gt_identity_cosine.dropna()),
        "MedGtCosineRhino": med(df[df.procedure == "rhinoplasty"].gt_identity_cosine.dropna()),
        "NumGtBaselineFaces": len(base),
        "MedGtBaseline": med(base.gt_baseline_cosine),
        "GtBaselineMin": fmt(base.gt_baseline_cosine.min()),
        "GtBaselineMax": fmt(base.gt_baseline_cosine.max()),
        "NumGtDeltaOutputs": len(gt_delta),
        "MedGtDelta": med(gt_delta.delta),
        **ci_macros("GtDelta", clustered_median_ci(gt_delta, "delta", "face_cluster")),
        "PctGtDeltaPositive": f"{(gt_delta.delta > 0).mean() * 100:.0f}",
        "MedLatency": med(df.latency_s, 0),
        "MedCost": med(df.cost_estimate_usd, 3),
    }

    write_text(
        TABLES_DIR / "numbers.tex",
        GENERATED_BY
        + "".join(f"\\newcommand{{\\{name}}}{{{value}}}\n" for name, value in macros.items()),
    )


def main() -> None:
    raw = load_runs()
    n_runs_total = raw.run_id.nunique()
    all_cells = dedupe(normalize(raw))
    n_attempted = len(all_cells)
    df = all_cells[all_cells.ok.eq(True) & all_cells.identity_cosine.notna()]

    keep = [
        "run_id", "stem", "face_id", "model", "procedure", "control",
        *METRIC_COLS, "latency_s", "cost_estimate_usd", "cached", "legacy_regions",
    ]
    DATA_DIR.mkdir(exist_ok=True)
    df[keep].to_csv(DATA_DIR / "canonical_rows.csv", index=False)

    write_main_results(df)
    write_setup_models()
    write_numbers(df, n_runs_total, df.run_id.nunique(), n_attempted)

    print(
        f"runs total={n_runs_total} scored={df.run_id.nunique()} "
        f"attempted cells={n_attempted} canonical rows={len(df)}"
    )
    print(df.groupby(["procedure", "model", "control"]).size().to_string())


if __name__ == "__main__":
    main()
